export const applicationLink = `div[class="card mt-4 top-card"]`;
export const learningJavascriptBook = `a[href="/books?book=9781449331818"]`;
export const details = `div[class*="col-md-9 col-sm-12"]`;
export const practiseFormButton = `div[class="element-list collapse show"]`;
export const formButton = `div[class="card mt-4 top-card"]`;
export const searchButton = `span[id="basic-addon2"]`;
export const searchField = `input[id="searchBox"]`;
export const formFirstNameTextBox = `#firstName`;
export const formLastNameTextBox = `#lastName`;
export const formEmailTextBox = `#userEmail`;
export const formGenderButton1 = `label[for="gender-radio-1"]`;
export const formGenderButton2 = `label[for="gender-radio-2"]`;
export const formGenderButton3 = `label[for="gender-radio-3"]`;
export const formMobileNumberTextBox = `input[placeholder="Mobile Number"]`;
export const formDOBTextBox = `input[id="dateOfBirthInput"]`;
export const formSubjectsTextBox = `div[class*="subjects-auto-complete__value-container"]`;
export const formHobbiesButtons = `div[class*="custom-control custom-checkbox custom-control-inline"]`;
export const formChooseFile = `input[id="uploadPicture"]`;
export const formCurrentAddress = `textarea[placeholder="Current Address"]`;
export const formCityStateTextBox = `div[class="col-md-4 col-sm-12"]`;
